export interface ProductVariant {
  id: string
  label: string
  detail: string
  price: number
  section: string
  isBundle: boolean
  deviceCount?: number
  bottleCount?: number
  capsuleCount?: number
  image?: string
}

export const products = [
  {
    id: 'circulation-support-device',
    name: 'Circulation Support Device',
    slug: 'circulation-support-device',
    category: 'device',
    description: 'A portable circulation-support device designed for everyday use, using gentle electrical stimulation and mild heat therapy to help support normal blood circulation in the legs and feet as part of a daily wellness routine. This device does not test, sample, or analyze blood in any way.',
    longDescription: 'Support healthy circulation from the comfort of home. The Circulation Support Device is designed for simple, everyday use, combining gentle electrical stimulation with mild heat therapy to help promote normal blood circulation in the legs and feet as part of a daily wellness routine.',
    features: [
      'Adjustable intensity levels for gentle stimulation',
      'Mild heat therapy function',
      'Compact, portable design for home use',
      'Simple power, mode, and intensity controls',
      'Rechargeable battery',
      'Includes user guide',
    ],
    image: '/images/products/device-1x.jpg',
    medicalDisclaimer: 'This product is a general wellness circulation-support device. It does not test, sample, diagnose, or analyze blood or any biological material. It is not a substitute for professional medical advice. Always consult a qualified healthcare provider regarding any health concerns, especially if you have a pacemaker or other implanted medical device.',
    defaultVariantId: 'single-device',
    variants: [
      {
        id: 'single-device',
        label: 'Circulation Support Device',
        detail: '1 Device',
        price: 47.89,
        section: 'Single Device Offer',
        isBundle: false,
        deviceCount: 1,
        image: '/images/products/device-1x.jpg',
      },
      {
        id: 'device-starter-support',
        label: 'Circulation Support Device + Starter Support',
        detail: '1 Device + 1 bottle / 30 capsules',
        price: 49.76,
        section: 'Device + Support Bundle Offers',
        isBundle: true,
        deviceCount: 1,
        bottleCount: 1,
        capsuleCount: 30,
        image: '/images/products/device-1x-supp30.jpg',
      },
      {
        id: 'device-standard-support',
        label: 'Circulation Support Device + Standard Support',
        detail: '1 Device + 1 bottle / 60 capsules',
        price: 53.45,
        section: 'Device + Support Bundle Offers',
        isBundle: true,
        deviceCount: 1,
        bottleCount: 1,
        capsuleCount: 60,
        image: '/images/products/device-1x-supp60.jpg',
      },
      {
        id: 'device-extended-support',
        label: 'Circulation Support Device + Extended Support',
        detail: '1 Device + 1 bottle / 90 capsules',
        price: 54.95,
        section: 'Device + Support Bundle Offers',
        isBundle: true,
        deviceCount: 1,
        bottleCount: 1,
        capsuleCount: 90,
        image: '/images/products/device-1x-supp90.jpg',
      },
      {
        id: '2-device-value-bundle',
        label: '2-Device Value Bundle',
        detail: '2 Devices',
        price: 86.88,
        section: 'Multi-Device Value Offers',
        isBundle: false,
        deviceCount: 2,
        image: '/images/products/device-2x.jpg',
      },
      {
        id: '2-device-starter-support-bundle',
        label: '2-Device + Starter Support Bundle',
        detail: '2 Devices + 1 bottle / 30 capsules',
        price: 87.64,
        section: 'Multi-Device Value Offers',
        isBundle: true,
        deviceCount: 2,
        bottleCount: 1,
        capsuleCount: 30,
        image: '/images/products/device-2x-supp30.jpg',
      },
      {
        id: '2-device-standard-support-bundle',
        label: '2-Device + Standard Support Bundle',
        detail: '2 Devices + 1 bottle / 60 capsules',
        price: 87.76,
        section: 'Multi-Device Value Offers',
        isBundle: true,
        deviceCount: 2,
        bottleCount: 1,
        capsuleCount: 60,
        image: '/images/products/device-2x-supp60.jpg',
      },
      {
        id: '2-device-extended-support-bundle',
        label: '2-Device + Extended Support Bundle',
        detail: '2 Devices + 1 bottle / 90 capsules',
        price: 94.82,
        section: 'Multi-Device Value Offers',
        isBundle: true,
        deviceCount: 2,
        bottleCount: 1,
        capsuleCount: 90,
        image: '/images/products/device-2x-supp90.jpg',
      },
      {
        id: '3-device-value-bundle',
        label: '3-Device Value Bundle',
        detail: '3 Devices',
        price: 96.95,
        section: 'Multi-Device Value Offers',
        isBundle: false,
        deviceCount: 3,
        image: '/images/products/device-3x.jpg',
      },
    ] satisfies ProductVariant[],
  },
  {
    id: 'blood-health-support-formula',
    name: 'Blood Health Support Formula',
    slug: 'blood-health-support-formula',
    category: 'supplement',
    description: 'A daily nutritional supplement formulated with iron, vitamin B12, and folate that provides supplemental support for normal nutritional needs related to healthy blood levels, as part of a balanced diet. This product is not intended to diagnose, treat, cure, or prevent any disease.',
    longDescription: 'A daily nutritional supplement with iron, vitamin B12, and folate that provides supplemental support for normal nutritional needs related to healthy blood levels, as part of a balanced diet.',
    features: [
      'Provides supplemental iron as part of a daily nutritional routine',
      'Contains vitamin B12 and folate to support normal nutritional needs',
      'Vitamin C included to help support iron absorption as part of a balanced diet',
      'Beet root extract included, traditionally used in daily wellness routines',
      'One capsule serving per day, easy to incorporate into a daily routine',
    ],
    image: '/images/supplements/Gemini_Generated_Image_9p5htz9p5htz9p5h.jpg',
    fdaDisclosure: 'These statements have not been evaluated by the Food and Drug Administration. This product is not intended to diagnose, treat, cure, or prevent any disease. Individual results may vary. Consult your physician before beginning any new supplement, especially if you have a medical condition, are pregnant or nursing, or are taking blood-thinning medication.',
    supplementDisclaimer: 'This product is not intended to diagnose, treat, cure, or prevent any disease. Individual results may vary. Consult your physician before beginning any new supplement.',
    defaultVariantId: 'standard-bottle',
    variants: [
      {
        id: 'starter-bottle',
        label: 'Starter Bottle',
        detail: '1 bottle / 30 capsules',
        price: 9.99,
        section: 'Regular Product Options',
        isBundle: false,
        bottleCount: 1,
        capsuleCount: 30,
        image: '/images/supplements/Gemini_Generated_Image_9p5htz9p5htz9p5h.jpg',
      },
      {
        id: 'standard-bottle',
        label: 'Standard Bottle',
        detail: '1 bottle / 60 capsules',
        price: 13.95,
        section: 'Regular Product Options',
        isBundle: false,
        bottleCount: 1,
        capsuleCount: 60,
        image: '/images/supplements/Gemini_Generated_Image_ahckiyahckiyahck.jpg',
      },
      {
        id: 'extended-bottle',
        label: 'Extended Bottle',
        detail: '1 bottle / 90 capsules',
        price: 14.75,
        section: 'Regular Product Options',
        isBundle: false,
        bottleCount: 1,
        capsuleCount: 90,
        image: '/images/supplements/Gemini_Generated_Image_b8gbp1b8gbp1b8gb.jpg',
      },
      {
        id: 'complete-bottle',
        label: 'Complete Bottle',
        detail: '1 bottle / 120 capsules',
        price: 17.95,
        section: 'Regular Product Options',
        isBundle: false,
        bottleCount: 1,
        capsuleCount: 120,
        image: '/images/supplements/Gemini_Generated_Image_mc4wufmc4wufmc4w.jpg',
      },
      {
        id: '2-bottle-value-bundle',
        label: '2-Bottle Value Bundle',
        detail: '2 bottles / 60 capsules per bottle / 120 capsules total',
        price: 18.75,
        section: 'Bundle Offers',
        isBundle: true,
        bottleCount: 2,
        capsuleCount: 120,
        image: '/images/supplements/Gemini_Generated_Image_qbde14qbde14qbde.jpg',
      },
      {
        id: '3-bottle-savings-bundle',
        label: '3-Bottle Savings Bundle',
        detail: '3 bottles / 60 capsules per bottle / 180 capsules total',
        price: 28.76,
        section: 'Bundle Offers',
        isBundle: true,
        bottleCount: 3,
        capsuleCount: 180,
        image: '/images/supplements/Gemini_Generated_Image_y18saxy18saxy18s.jpg',
      },
      {
        id: '4-bottle-best-value-bundle',
        label: '4-Bottle Best Value Bundle',
        detail: '4 bottles / 60 capsules per bottle / 240 capsules total',
        price: 38.64,
        section: 'Bundle Offers',
        isBundle: true,
        bottleCount: 4,
        capsuleCount: 240,
        image: '/images/supplements/Gemini_Generated_Image_z4dqzbz4dqzbz4dq.jpg',
      },
    ] satisfies ProductVariant[],
  },
] as const

export type Product = typeof products[number]

export function getDefaultVariant(product: Product): ProductVariant {
  return product.variants.find((v) => v.id === product.defaultVariantId) ?? product.variants[0]
}

export function getStartingPrice(product: Product): number {
  return Math.min(...product.variants.map((v) => v.price))
}
